RUN_NAME: 'rafdb'

SKIP_SAVE: False
RECOMPUTE_ALL: True
RECOMPUTE_NUM_DEP: True

DATASET:
  NAME: 'rafdb'
  TRANSFORM_NAME: 'CLD-rafdb'

MODEL:
  ARCH: 'ResNet50'
  PRETRAIN_PATH: 'pretrained/cifar10_ckpt_epoch_200.pth'

USL:
  NUM_SELECTED_SAMPLES: 40
  KNN_K: 400
  SEEDS: [1, 2, 3, 4, 5]
